
/* INCLUDES *******************************************************************/

#include <hal.h>
//#define NDEBUG
#include <debug.h>

/* INCLUDES *******************************************************************/

typedef enum _EXTENSION_TYPE
{
    PdoExtensionType = 0xC0,
    FdoExtensionType
} EXTENSION_TYPE;

typedef enum _PDO_TYPE
{
    AcpiPdo = 0x81,
    WdPdo = 0x82
} PDO_TYPE;

typedef struct _FDO_EXTENSION
{
    EXTENSION_TYPE ExtensionType;
    struct _PDO_EXTENSION* ChildPdoList;
    PDEVICE_OBJECT PhysicalDeviceObject;
    PDEVICE_OBJECT FunctionalDeviceObject;
    PDEVICE_OBJECT AttachedDeviceObject;
} FDO_EXTENSION, *PFDO_EXTENSION;

typedef struct _PDO_EXTENSION
{
    EXTENSION_TYPE ExtensionType;
    struct _PDO_EXTENSION* Next;
    PDEVICE_OBJECT PhysicalDeviceObject;
    PFDO_EXTENSION ParentFdoExtension;
    PDO_TYPE PdoType;
    PDESCRIPTION_HEADER WdTable;
    LONG InterfaceReferenceCount;
} PDO_EXTENSION, *PPDO_EXTENSION;

/* GLOBALS ********************************************************************/

PDRIVER_OBJECT HalpDriverObject;

/* PRIVATE FUNCTIONS **********************************************************/

NTSTATUS
NTAPI
HalpAddDevice(
    _In_ PDRIVER_OBJECT DriverObject,
    _In_ PDEVICE_OBJECT TargetDevice)
{
    PDEVICE_OBJECT FdoDeviceObject;
    PDEVICE_OBJECT AttachedDevice;
    PDEVICE_OBJECT PdoDeviceObject;
    PDEVICE_OBJECT WdDeviceObject;
    PFDO_EXTENSION FdoExtension;
    PPDO_EXTENSION PdoExtension;
    PPDO_EXTENSION WdExtension;
    PDESCRIPTION_HEADER Wdrt;
    NTSTATUS Status;

    PAGED_CODE();
    DPRINT("HalpAddDevice: Driver %p, Pdo %p\n", DriverObject, TargetDevice);

    /* Create the FDO */
    Status = IoCreateDevice(DriverObject,
                            sizeof(FDO_EXTENSION),
                            NULL,
                            FILE_DEVICE_BUS_EXTENDER,
                            0,
                            FALSE,
                            &FdoDeviceObject);
    if (!NT_SUCCESS(Status))
    {
        /* Should not happen */
        DPRINT1("HalpAddDevice: Status %X\n", Status);
        ASSERT(FALSE);//HalpDbgBreakPointEx();
        return Status;
    }

    DPRINT("HalpAddDevice: Fdo %p\n", FdoDeviceObject);

    /* Setup the FDO extension */
    FdoExtension = FdoDeviceObject->DeviceExtension;
    FdoExtension->ExtensionType = FdoExtensionType;
    FdoExtension->PhysicalDeviceObject = TargetDevice;
    FdoExtension->FunctionalDeviceObject = FdoDeviceObject;
    FdoExtension->ChildPdoList = NULL;

    /* FDO is done initializing */
    FdoDeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;

    /* Attach to the physical device object (the bus) */
    AttachedDevice = IoAttachDeviceToDeviceStack(FdoDeviceObject, TargetDevice);
    if (!AttachedDevice)
    {
        /* Failed, undo everything */
        DPRINT("HalpAddDevice: return STATUS_NO_SUCH_DEVICE\n");
        IoDeleteDevice(FdoDeviceObject);
        return STATUS_NO_SUCH_DEVICE;
    }

    DPRINT("HalpAddDevice: AttachedDevice %p\n", AttachedDevice);

    /* Save the attachment */
    FdoExtension->AttachedDeviceObject = AttachedDevice;

    /* Create the PDO */
    Status = IoCreateDevice(DriverObject,
                            sizeof(PDO_EXTENSION),
                            NULL,
                            FILE_DEVICE_BUS_EXTENDER,
                            FILE_AUTOGENERATED_DEVICE_NAME,
                            FALSE,
                            &PdoDeviceObject);
    if (!NT_SUCCESS(Status))
    {
        /* Fail */
        DPRINT1("HalpAddDevice: Not created ACPI PDO. Sts %X\n", Status);
        return Status;
    }

    DPRINT("HalpAddDevice: IoCreateDevice ACPI PDO %p\n", PdoDeviceObject);

    /* Setup the PDO device extension */
    PdoExtension = PdoDeviceObject->DeviceExtension;
    PdoExtension->ExtensionType = PdoExtensionType;
    PdoExtension->PhysicalDeviceObject = PdoDeviceObject;
    PdoExtension->ParentFdoExtension = FdoExtension;
    PdoExtension->PdoType = AcpiPdo;

    /* Add the PDO to the head of the list */
    PdoExtension->Next = NULL;

    /* Find the ACPI watchdog table */
    Wdrt = HalAcpiGetTable(0, 'TRDW');
    if ( !Wdrt )
    {
        /* Initialization is finished */
        DPRINT1("HalpAddDevice: No Watchdog.\n");
        goto Exit;
    }

    /* FIXME: TODO */
    DPRINT1("HalpAddDevice: You have an ACPI Watchdog.  ... \n");
    ASSERT(FALSE);//HalpDbgBreakPointEx();

    Status = IoCreateDevice(DriverObject,
                            sizeof(PDO_EXTENSION),
                            NULL,
                            FILE_DEVICE_BUS_EXTENDER,
                            FILE_AUTOGENERATED_DEVICE_NAME,
                            FALSE,
                            &WdDeviceObject);
    if (!NT_SUCCESS(Status))
    {
        DPRINT1("HalpAddDevice: Not created WD DO. Status %X\n", Status);
        IoDeleteDevice(PdoDeviceObject);
        return Status;
    }

    DPRINT("HalpAddDevice: IoCreateDevice Wd DO %p\n", WdDeviceObject);

    WdExtension = WdDeviceObject->DeviceExtension;
    WdExtension->ExtensionType = PdoExtensionType;
    WdExtension->PhysicalDeviceObject = WdDeviceObject;
    WdExtension->ParentFdoExtension = FdoExtension;
    WdExtension->PdoType = WdPdo;
    WdExtension->WdTable = Wdrt;

    WdExtension->Next = NULL;
    PdoExtension->Next = WdExtension;

    WdDeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;

Exit:

    PdoDeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;
    FdoExtension->ChildPdoList = PdoExtension;

    DPRINT("HalpAddDevice: return STATUS_SUCCESS\n");
    return STATUS_SUCCESS;
}

NTSTATUS
NTAPI
HalpDispatchPnp(
    _In_ PDEVICE_OBJECT DeviceObject,
    _In_ PIRP Irp)
{
    UNIMPLEMENTED;
    ASSERT(FALSE); // HalpDbgBreakPointEx();
    return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS
NTAPI
HalpDispatchWmi(
    _In_ PDEVICE_OBJECT DeviceObject,
    _In_ PIRP Irp)
{
    UNIMPLEMENTED;
    ASSERT(FALSE); // HalpDbgBreakPointEx();
    return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS
NTAPI
HalpDispatchPower(
    _In_ PDEVICE_OBJECT DeviceObject,
    _In_ PIRP Irp)
{
    UNIMPLEMENTED;
    ASSERT(FALSE); // HalpDbgBreakPointEx();
    return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS
NTAPI
HalpDriverEntry(
    _In_ PDRIVER_OBJECT DriverObject,
    _In_ PUNICODE_STRING RegistryPath)
{
    NTSTATUS Status;
    PDEVICE_OBJECT TargetDevice = NULL;

    PAGED_CODE();
    DPRINT("HalpDriverEntry: DriverObject %p, '%wZ'\n", DriverObject, RegistryPath);

    /* This is us */
    HalpDriverObject = DriverObject;

    /* Set up add device */
    DriverObject->DriverExtension->AddDevice = HalpAddDevice;

    /* Set up the callouts */
    DriverObject->MajorFunction[IRP_MJ_PNP] = HalpDispatchPnp;
    DriverObject->MajorFunction[IRP_MJ_POWER] = HalpDispatchPower;
    DriverObject->MajorFunction[IRP_MJ_SYSTEM_CONTROL] = HalpDispatchWmi;

    /* Tell the PnP manager about us */
    Status = IoReportDetectedDevice(DriverObject,
                                    InterfaceTypeUndefined,
                                    -1,
                                    -1,
                                    NULL,
                                    NULL,
                                    FALSE,
                                    &TargetDevice);

    DPRINT("HalpDriverEntry: TargetDevice %p\n", TargetDevice);
    ASSERT(TargetDevice);

    if (!NT_SUCCESS(Status))
    {
        DPRINT1("HalpDriverEntry: Status %X\n", Status);
        ASSERT(FALSE);
        return Status;
    }

    HalpAddDevice(DriverObject, TargetDevice);

    /* Return to kernel */
    return STATUS_SUCCESS;
}

/* FUNCTIONS ******************************************************************/

NTSTATUS
NTAPI
HaliInitPnpDriver(VOID)
{
    NTSTATUS Status;
    UNICODE_STRING DriverString;

    DPRINT("HaliInitPnpDriver()\n");
    PAGED_CODE();

    /* Create the driver */
    RtlInitUnicodeString(&DriverString, L"\\Driver\\ACPI_HAL");

    Status = IoCreateDriver(&DriverString, HalpDriverEntry);
    ASSERT(NT_SUCCESS(Status));

    /* Return status */
    return Status;
}

/* EOF */
