@ fastcall ExAcquireFastMutex(ptr) ntoskrnl.ExiAcquireFastMutex
@ fastcall ExReleaseFastMutex(ptr) ntoskrnl.ExiReleaseFastMutex
@ fastcall ExTryToAcquireFastMutex(ptr) ntoskrnl.ExiTryToAcquireFastMutex
@ stdcall HalAdjustResourceList(ptr)
@ stdcall HalAllProcessorsStarted()
@ stdcall HalAllocateAdapterChannel(ptr ptr long ptr)
@ stdcall HalBeginSystemInterrupt(long long ptr)
@ fastcall HalClearSoftwareInterrupt(long)
@ stdcall HalDisableSystemInterrupt(long long)
@ stdcall HalDisplayString(str)
@ stdcall HalEnableSystemInterrupt(long long long)
@ stdcall HalEndSystemInterrupt(long long) #NT use nonstandard parameters calling
@ stdcall HalGetEnvironmentVariable(str long str)
@ stdcall HalGetInterruptVector(long long long long ptr ptr)
@ stdcall HalHandleNMI(ptr)
@ stdcall HalInitSystem(long ptr)
@ stdcall HalInitializeProcessor(long ptr)
@ stdcall HalProcessorIdle()
@ stdcall HalQueryRealTimeClock(ptr)
@ stdcall HalReportResourceUsage()
@ stdcall HalRequestIpi(long)
@ fastcall HalRequestSoftwareInterrupt(long)
@ stdcall HalReturnToFirmware(long)
@ stdcall HalSetEnvironmentVariable(str str)
@ stdcall HalSetProfileInterval(long)
@ stdcall HalSetRealTimeClock(ptr)
@ stdcall HalSetTimeIncrement(long)
@ stdcall HalStartNextProcessor(ptr ptr)
@ stdcall HalStartProfileInterrupt(long)
@ stdcall HalStopProfileInterrupt(long)
@ fastcall HalSystemVectorDispatchEntry(long long long)
@ stdcall HalTranslateBusAddress(long long long long ptr ptr)
@ extern KdComPortInUse
@ fastcall KeAcquireInStackQueuedSpinLock(ptr ptr)
@ fastcall KeAcquireInStackQueuedSpinLockRaiseToSynch(ptr ptr)
@ fastcall KeAcquireQueuedSpinLock(ptr)
@ fastcall KeAcquireQueuedSpinLockRaiseToSynch(ptr)
@ stdcall KeAcquireSpinLock(ptr ptr)
@ fastcall KeAcquireSpinLockRaiseToSynch(ptr)
@ stdcall KeGetCurrentIrql()
@ stdcall KeFlushWriteBuffer()
@ stdcall KeLowerIrql(long)
@ stdcall KeQueryPerformanceCounter(ptr)
@ stdcall KeRaiseIrql(long ptr)
@ stdcall KeRaiseIrqlToDpcLevel()
@ stdcall KeRaiseIrqlToSynchLevel()
@ fastcall KfLowerIrql(long)
@ fastcall KfRaiseIrql(long)
@ stdcall READ_PORT_BUFFER_UCHAR(ptr ptr long)
@ stdcall READ_PORT_BUFFER_ULONG(ptr ptr long)
@ stdcall READ_PORT_BUFFER_USHORT(ptr ptr long)
@ stdcall READ_PORT_UCHAR(ptr)
@ stdcall READ_PORT_ULONG(ptr)
@ stdcall READ_PORT_USHORT(ptr)
@ stdcall WRITE_PORT_BUFFER_UCHAR(ptr ptr long)
@ stdcall WRITE_PORT_BUFFER_ULONG(ptr ptr long)
@ stdcall WRITE_PORT_BUFFER_USHORT(ptr ptr long)
@ stdcall WRITE_PORT_UCHAR(ptr long)
@ stdcall WRITE_PORT_ULONG(ptr long)
@ stdcall WRITE_PORT_USHORT(ptr long)
