@ fastcall ExAcquireFastMutex(ptr) ntoskrnl.ExiAcquireFastMutex
@ fastcall ExReleaseFastMutex(ptr) ntoskrnl.ExiReleaseFastMutex
@ fastcall ExTryToAcquireFastMutex(ptr) ntoskrnl.ExiTryToAcquireFastMutex
@ stdcall HalAdjustResourceList(ptr)
@ stdcall HalAllProcessorsStarted()
@ stdcall HalAllocateAdapterChannel(ptr ptr long ptr)
@ stdcall HalBeginSystemInterrupt(long long ptr)
@ fastcall HalClearSoftwareInterrupt(long)
@ stdcall HalDisableSystemInterrupt(long long)
@ stdcall HalDisplayString(str)
@ stdcall HalInitSystem(long ptr)
@ stdcall HalInitializeProcessor(long ptr)
@ stdcall HalProcessorIdle()
@ stdcall HalRequestIpi(long)
@ stdcall HalStartNextProcessor(ptr ptr)
@ fastcall HalSystemVectorDispatchEntry(long long long)
@ stdcall KeGetCurrentIrql()
@ stdcall KeFlushWriteBuffer()
@ fastcall KfRaiseIrql(long)
@ stdcall READ_PORT_BUFFER_UCHAR(ptr ptr long)
@ stdcall READ_PORT_BUFFER_ULONG(ptr ptr long)
@ stdcall READ_PORT_BUFFER_USHORT(ptr ptr long)
@ stdcall READ_PORT_UCHAR(ptr)
@ stdcall READ_PORT_ULONG(ptr)
@ stdcall READ_PORT_USHORT(ptr)
@ stdcall WRITE_PORT_BUFFER_UCHAR(ptr ptr long)
@ stdcall WRITE_PORT_BUFFER_ULONG(ptr ptr long)
@ stdcall WRITE_PORT_BUFFER_USHORT(ptr ptr long)
@ stdcall WRITE_PORT_UCHAR(ptr long)
@ stdcall WRITE_PORT_ULONG(ptr long)
@ stdcall WRITE_PORT_USHORT(ptr long)
