
 @ stdcall FltRegisterFilter(ptr ptr ptr)
 @ stdcall FltUnregisterFilter(ptr)
 @ stdcall FltStartFiltering(ptr)
 @ stdcall FltGetFilterFromInstance(ptr ptr)
 @ stdcall FltBuildDefaultSecurityDescriptor(ptr long)
 @ stdcall FltFreeSecurityDescriptor(ptr)
 @ stdcall FltGetDeviceObject(ptr ptr)
 @ stdcall FltGetDiskDeviceObject(ptr ptr)
 @ stdcall FltGetVolumeProperties(ptr ptr long ptr)
 @ stdcall FltObjectDereference(ptr)
 @ stdcall FltDeletePushLock(ptr)
 @ stdcall FltSendMessage(ptr ptr ptr long ptr ptr ptr)
 @ stdcall FltEnumerateVolumes(ptr ptr long ptr)
 @ stdcall FltGetFileNameInformationUnsafe(ptr ptr long ptr)
 @ stdcall FltQueryInformationFile(ptr ptr ptr long long long)
 @ stdcall FltSetInformationFile(ptr ptr ptr long ptr)
 @ stdcall FltCloseClientPort(ptr ptr)
 @ stdcall FltClose(ptr)
 @ stdcall FltCreateFileEx(ptr ptr ptr ptr long ptr ptr ptr long long long long ptr long long)
 @ stdcall FltCreateFile(ptr ptr ptr long ptr ptr ptr long long long long ptr long long)
 @ stdcall FltReadFile(ptr ptr ptr long ptr long long ptr ptr)
 @ stdcall FltWriteFile(ptr ptr ptr long ptr long ptr ptr ptr)
 @ stdcall FltFsControlFile(ptr ptr long ptr long ptr long long)
 @ stdcall FltCancelFileOpen(ptr ptr)
 @ stdcall FltDetachVolume(ptr ptr ptr)
 @ stdcall FltGetVolumeName(ptr ptr ptr)
 @ stdcall FltGetVolumeGuidName(ptr ptr ptr)
 @ stdcall FltGetVolumeFromName(ptr ptr ptr)
 @ stdcall FltGetVolumeFromFileObject(ptr ptr ptr)
 @ stdcall FltGetVolumeFromInstance(ptr ptr)
 @ stdcall FltGetVolumeContext(ptr ptr ptr)
 @ stdcall FltSetVolumeContext(ptr long ptr ptr)
 @ stdcall FltIsVolumeWritable(ptr ptr)
 @ stdcall FltCreateSystemVolumeInformationFolder(ptr)
 @ stdcall FltEnumerateVolumeInformation(ptr long long ptr long long)
 @ stdcall FltQueryVolumeInformationFile(ptr ptr ptr long ptr long)
 @ stdcall FltQuerySecurityObject(ptr ptr long ptr long long)
 @ stdcall FltQueueGenericWorkItem(ptr ptr ptr ptr ptr)
 @ stdcall FltSetSecurityObject(ptr ptr ptr ptr)
 @ stdcall FltGetFileNameInformation(ptr long ptr)
 @ stdcall FltAllocateContext(ptr long long long ptr)
 @ stdcall FltReferenceContext(ptr)
 @ stdcall FltReleaseContext(ptr)
 @ stdcall FltGetInstanceContext(ptr ptr)
 @ stdcall FltSetInstanceContext(ptr long ptr ptr)
 @ stdcall FltGetStreamContext(ptr ptr ptr)
 @ stdcall FltSetStreamContext(ptr ptr long ptr ptr)
 @ stdcall FltGetStreamHandleContext(ptr ptr ptr)
 @ stdcall FltSetStreamHandleContext(ptr ptr long ptr ptr)
 @ stdcall FltSupportsStreamHandleContexts(ptr)
 @ stdcall FltCreateCommunicationPort(ptr ptr ptr ptr ptr ptr ptr long)
 @ stdcall FltCloseCommunicationPort(ptr)
 @ stdcall FltAttachVolume(ptr ptr ptr ptr)
 @ stdcall FltGetDestinationFileNameInformation(ptr ptr ptr ptr long long ptr)
 @ stdcall FltParseFileNameInformation(ptr)
 @ stdcall FltReferenceFileNameInformation(ptr)
 @ stdcall FltReleaseFileNameInformation(ptr)
 @ stdcall FltGetRoutineAddress(str)
 @ stdcall FltGetTopInstance(ptr ptr)
 @ stdcall FltEnumerateInstances(ptr ptr ptr long long)
 @ stdcall FltAllocateGenericWorkItem()
 @ stdcall FltFreeGenericWorkItem(ptr)
 @ stdcall FltAllocatePoolAlignedWithTag(ptr long long long)
 @ stdcall FltFreePoolAlignedWithTag(ptr ptr long)
 @ stdcall FltAllocateCallbackData(ptr ptr ptr)
 @ stdcall FltFreeCallbackData(ptr)
 @ stdcall FltIsCallbackDataDirty(ptr)
 @ stdcall FltClearCallbackDataDirty(ptr)
 @ stdcall FltSetCallbackDataDirty(ptr)
 @ stdcall FltInitializePushLock(ptr)
 @ stdcall FltLockUserBuffer(ptr)
 @ stdcall FltFlushBuffers(ptr ptr)
 @ stdcall FltPerformSynchronousIo(ptr)
 @ stdcall FltGetRequestorProcess(ptr)
 @ stdcall FltGetRequestorProcessId(ptr)

