
 @ stdcall FltRegisterFilter(ptr ptr ptr)
 @ stdcall FltUnregisterFilter(ptr)
 @ stdcall FltStartFiltering(ptr)
 @ stdcall FltBuildDefaultSecurityDescriptor(ptr long)
 @ stdcall FltFreeSecurityDescriptor(ptr)
 @ stdcall FltGetDeviceObject(ptr ptr)
 @ stdcall FltGetDiskDeviceObject(ptr ptr)
 @ stdcall FltGetVolumeProperties(ptr ptr long ptr)
 @ stdcall FltObjectDereference(ptr)
 @ stdcall FltSendMessage(ptr ptr ptr long ptr ptr ptr)
 @ stdcall FltEnumerateVolumes(ptr ptr long ptr)
 @ stdcall FltGetFileNameInformationUnsafe(ptr ptr long ptr)
 @ stdcall FltSetInformationFile(ptr ptr ptr long ptr)
 @ stdcall FltCloseClientPort(ptr ptr)
 @ stdcall FltClose(ptr)
 @ stdcall FltCreateFileEx(ptr ptr ptr ptr long ptr ptr ptr long long long long ptr long long)
 @ stdcall FltCreateFile(ptr ptr ptr long ptr ptr ptr long long long long ptr long long)
 @ stdcall FltReadFile(ptr ptr ptr long ptr long long ptr ptr)
 @ stdcall FltWriteFile(ptr ptr ptr long ptr long ptr ptr ptr)
 @ stdcall FltDetachVolume(ptr ptr ptr)
 @ stdcall FltGetVolumeName(ptr ptr ptr)
 @ stdcall FltQueryVolumeInformationFile(ptr ptr ptr long ptr long)
 @ stdcall FltQuerySecurityObject(ptr ptr long ptr long long)
 @ stdcall FltSetSecurityObject(ptr ptr ptr ptr)
 @ stdcall FltGetFileNameInformation(ptr long ptr)
 @ stdcall FltGetStreamHandleContext(ptr ptr ptr)
 @ stdcall FltSupportsStreamHandleContexts(ptr)
 @ stdcall FltCreateCommunicationPort(ptr ptr ptr ptr ptr ptr ptr long)
 @ stdcall FltCloseCommunicationPort(ptr)
 @ stdcall FltAttachVolume(ptr ptr ptr ptr)
 @ stdcall FltGetDestinationFileNameInformation(ptr ptr ptr ptr long long ptr)
 @ stdcall FltParseFileNameInformation(ptr)
 @ stdcall FltReleaseFileNameInformation(ptr)
 @ stdcall FltIsCallbackDataDirty(ptr)
 @ stdcall FltSetCallbackDataDirty(ptr)

